##############################################################################
# COPYRIGHT(C)	: Samsung Electronics Co.Ltd, 2006-2011 ALL RIGHTS RESERVED
# AUTHOR		: Varun Mahajan <m.varun@samsung.com>
##############################################################################
# VERSION&DATE	: Version 0.1
##############################################################################

EXTRA_CFLAGS	+= -I$(srctree)/drivers/staging/android
obj-$(CONFIG_FMRADIO) +=  Si4709_dev.o 	Si4709_i2c_drv.o Si4709_main.o