#
# Makefile for the Samsung Proximity/Light Sensor driver
#
obj-$(CONFIG_SAMSUNG_PROXIMITY_LIGHT) += PL_sensor.o
PL_sensor-y :=
PL_sensor-y += main.o
PL_sensor-y += i2c_drv.o
PL_sensor-y += L_dev.o
PL_sensor-y += P_dev.o
PL_sensor-y += PL_power.o
